---
- name: create a user account
  hosts: production
  tasks:
    - name:  create user nene
      user:
        name: nene

    - name: nene to the wheel group
      user:
       name:  nene
       groups: wheel
